CREATE DATABASE DB_PADARIA;
USE DB_PADARIA;


CREATE TABLE TB_ADMINISTRADOR( 
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(30) NOT NULL UNIQUE,
    Senha VARCHAR(30) NOT NULL 
);
INSERT INTO TB_ADMINISTRADOR(NOME,SENHA) VALUES("ADMIN", "ADMIN");

CREATE TABLE TB_PRODUTOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    PRODUTO VARCHAR(200) NOT NULL UNIQUE,
    PRECO INT NOT NULL
);

CREATE TABLE TB_FACTURA(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    IDPRODUTO INT NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRECO INT NOT NULL,
    TOTAL INT,
    DATA_DA_VENDA DATE NOT NULL,
    FOREIGN KEY(IDPRODUTO)
    REFERENCES TB_PRODUTOS(ID)
);


CREATE TABLE TB_ESTOQUE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ESTOQUE INT NOT NULL,
    IDPRODUTO INT NOT NULL,
    FOREIGN KEY (IDPRODUTO) 
    REFERENCES PRODUTO(ID)
);

/*WAMP SERVER*/
DELIMITER $
CREATE TRIGGER CALCULARPRECO BEFORE INSERT ON TB_FACTURA
FOR EACH ROW
BEGIN
    UPDATE TB_FACTURA SET TOTAL = NEW.PRECO * NEW.QUANTIDADE
    WHERE ID = NEW.ID;
END
$



/*SOMA COLUNA TOTAL*/
SELECT SUM(TOTAL) FROM TB_FACTURA 
WHERE DATA_DA_VENDA = '?'  